### ISSUE TITLE
Asiento: codigoDeAsiento/codDeVuelo y esClaseAsiento(Clase[] clases)

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#10]
Como se habia hecho, el codigo de asiento vendria a ser algo como: `"ECO-24"` donde `24` era el *numeroDeAsiento* de ese codigo.
Para hacerlo mas sencillo, me gustaria pasar solamente el *numeroDeAsiento*, sin el *codDeVuelo*: `"ECO"` ya que eso lo tiene el **Vuelo**. En la busqueda/compra/reserva se podria unir ambos strings para formar `"ECO-24"` pero mientras tanto: 
* si se pide el *codDeVuelo* al **Asiento** te mandara `Vuelo.getCodDeVuelo()` **-return: "ECO"-**
* si se pide el *codigoDeAsiento* al **Asiento** te mandara su `numeroDeAsiento`. **-return: "24"-**

Por otro lado, no se muy bien que hace `esClaseAsiento(Clase[] clases)` asi que decidi dejarlo como estaba pero como tenia comentados cambios, hace falta hacerlos.

**Comment by MattVezz** [comment]
esClaseAsiento(Clase[] clases)
Recibe un array de clases y se fija si el asiento esta dentro de esas clases.
Sino devuelve false.
Se usa para filtrar por clase de asiento.

**Comment by aleanvalle** [comment]
Parece que lo dije antes de hablar de: esClaseAsiento(Clase[] clases). Es medio chino, pero ya esta (creo).
esClaseAsiento(Clase[] clases) esta en Asiento y AsientoDTO. Si estan duplicadas en ambas clases no tiene mucho sentido ya que se heredan y estas sobreescribiendo el mismo codigo.
Veo la anotacion: *//arreglar condicion de corte en FOR cambiar a Lista*

Ahi lo reemplace con lo que pude entender y saque la duplicacion. 5eda52e835aca79ef81d6eaa0d2043a02a879f39
