### ISSUE TITLE
[Entrega 4 Correcciones] Eliminar CodDeAsiento del metodo reservar...

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#11]
# Pasarle el asiento para que sea mas claro.
# El metodo no va a cambiar pero sus parametros pueden.

**Comment by MattVezz** [comment]
Arrancado. Me falta quitar el de reservar todavia, porque tiene el metodo de transferir reserva.

**Comment by aleanvalle** [comment]
97f903b0a6286cc41b5f485bcda151f771d9db97 - Si todo esta bien, entonces cierro esto tambien.
