### ISSUE TITLE
[Entrega 4 Correcciones] Funciona el app/viewmodel?: Agregar_busqueda/comprar/reservar (Ventana de Busqueda de asientos)

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#21]
Tengo anotado que ya se validaba la busqueda...

**Comment by MattVezz** [comment]
Ya funciona la pantalla de busqueda. Trabajando en el comprar y reservar.

**Comment by aleanvalle** [comment]
Me fije y creo que falta una ventana/dialog cuando seleccionas el asiento en BuscarAsientos te diga "Usted compro un asiento" si se presiona Comprar. O algo asi, creo que estaba en el tp escrito...

**Comment by aleanvalle** [comment]
> Me fije y creo que falta una ventana/dialog cuando seleccionas el asiento en BuscarAsientos te diga "Usted compro un asiento" si se presiona Comprar. O algo asi, creo que estaba en el tp escrito...

Dejando de lado lo que dije hace casi una semana, funciona esto?

**Comment by MattVezz** [comment]
Ya esta hecho. Ahora funciona. lo que no hace es sobrereservar.
Porque traigo solo los asientos disponibles

**Comment by MattVezz** [comment]
Si alguno lo quiere probar. Le puse un par de cosas de quality of life, para que no parezca tan chota la app

**Comment by aleanvalle** [comment]
faef23323c55be1d6c84b6b3ab3f38bf1a611e82 y e140ae6bad7ee6536f04b39f2ba9a8c4f967f41f - Cerrado
