### ISSUE TITLE
[Entrega 4 Correcciones] "Aerolinea" deberia llamarse de otra forma mas concreta.

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#22]
La profe dijo que estaba poco claro ese nombre. "Busqueda" fue una sugerencia que recuerdo que dijo.

**Comment by MattVezz** [comment]
Propongo AgenteViajes o IntermediarioPasajes o algo por el estilo

**Comment by aleanvalle** [comment]
7f4f0ccfdffedd6d22f064d4b9bb247227354f9b - Aerolinea -> AterrizarTramitesDeAsientos
Sera mas largo para escribir pero es mas claro.
