### ISSUE TITLE
Separar la Busqueda/Compra/Reserva en cosas mas chicas

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#4]
# Usar objetos. No usar Ifs. Refactorizar si es necesario.

**Comment by aleanvalle** [comment]
207e8f38e0e888dad06ec47f4a9ddd5b15dc8b20 - Mejoro bastante.
Reemplazo el Resolver por Cambiar.

**Comment by MattVezz** [comment]
Como decía en el ws, me falta la parte de transferencia de reserva.
@IvanMarcosSalomon  podras verlo vos??

**Comment by aleanvalle** [comment]
97f903b0a6286cc41b5f485bcda151f771d9db97 - Completado supongo. Mucho mejor que antes esta: :100:
