### ISSUE TITLE
Integrar las Busquedas/Compras... de AerolineaLanchita y Oceanic

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#5]

**Comment by MattVezz** [comment]
Integre las busquedas, solo cuando no se ponen opcionales.
Asiendo que AsientoDTO herede de Asiento. Si esta bien esta idea sigo con las compras

**Comment by aleanvalle** [comment]
Ya termine todo lo relacionado a oceanic. Podes seguir. :100: 
(estos emojis...)

**Comment by aleanvalle** [comment]
Esto esta relacionado a #13

**Comment by aleanvalle** [comment]
1906e84b6e31b560485d545413eb3f7c8c6dc4b3 - Tal vez con este cambio se pueda seguir con reserva y compra para que sea indistinto tambien. Sigo mañana.

**Comment by MattVezz** [comment]
Queda este solo?
Hacer que las reservas  y compras sean integradas.

**Comment by aleanvalle** [comment]
af403a74883ac3497619ddad13657358f58f590d - Cerrado
