### ISSUE TITLE
Herencia grafica??

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#6]
# Cuarta entrega: 25 de junio. (Grupal)

**Comment by aleanvalle** [comment]
Subidos packages con pruebas para empezar...

**Comment by IvanMarcosSalomon** [comment]
Yo estoy haciendo las vistas, mañana llevo todas las ventanas para empezar con el codigo

**Comment by aleanvalle** [comment]
> # Cuarta entrega: 25 de junio. (Grupal)

Ahora es 11 de julio (creo)

**Comment by MattVezz** [comment]
Falta hacer la vista con herencia grafica.

**Comment by aleanvalle** [comment]
> Falta hacer la vista con herencia grafica.

04601dd37614ee1bf99192de24b17cfc0705e03b - Esto no era? No estoy seguro...

**Comment by aleanvalle** [comment]
04601dd37614ee1bf99192de24b17cfc0705e03b - Si era esto.
