### ISSUE TITLE
buscarAsientoTest no ordena listas y fallan 2 de sus test, arreglar.

### ISSUE THREAD

**Issue by aleanvalle** [AlexisLeandroVallejos/TPAterrizar#9]
No se si los test que "ordenaban" ordenaban en primer lugar, ya que ni el precio o tiempo de vuelo se ordena. La lista sale y queda igual como entra al comparador.

**Comment by MattVezz** [comment]
Cerrado en commit.
9d27e261f240fa7fac16bc2cb0e42105ec6830c6
